---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lxy.
--- DateTime: 2025/11/17 11:27
---
-- 1.1.优惠券id
local voucherId = ARGV[1]
-- 1.2.用户id
local userId = ARGV[2]
-- 1.3.订单id
local orderId = ARGV[3]


-- 2.1.库存key
local stockkey = 'seckill:stock:' .. voucherId
-- 2.2.订单key
local orderkey = 'seckill:order:' .. voucherId

-- 3.脚本业务
if(tonumber(redis.call('get', stockkey)) <= 0) then
    return 1
end
if(redis.call('sismember', orderkey, userId) == 1) then
    return 2
end
redis.call('incrby', stockkey, -1)

redis.call('sadd', orderkey, userId)

redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)

return 0












