---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lxy.
--- DateTime: 2025/11/15 16:30
---比较线程标识与锁中的标识是否一致
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0